FROM python:3.10-slim-buster as Builder

WORKDIR /backend

ENV PYTHONUNVUFFERED 1
ENV PYTHONDONTWEITBYTECODE 1

RUN apt-get update \
    && apt-get install -y \
       pkg-config \
       default-libmysqlclient-dev \
       gcc \
       python3-dev
RUN pip install --upgrade pip

COPY requirements.txt .

FROM python:3.10-slim-buster