version: "3.8"

services:
  nginx-rp-gateway:
    container_name: nginx-rp-gateway
    hostname: nginx-rp-gateway
    image: nginx
    ports:
      - 80:8080
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
networks:
  default:
    name: nginx_reverse_proxy_gateway
